version: "3"
volumes:
  mailbox:
  sqlite:
services:
  smtp-sink:
    image: camptocamp/smtp-sink
    container_name: smtp-sink
    ports:
      - "2525:25"
    volumes:
      - mailbox:/home/smtp/Maildir/

  courier-imap:
    image: camptocamp/courier-imap
    container_name: courier-imap
    ports:
      - "143:143"
    volumes:
      - mailbox:/home/smtp/Maildir/

  webmail:
    image: camptocamp/roundcube
    container_name: webmail
    environment:
      - IMAP_HOSTNAME=courier-imap
      - SMTP_HOSTNAME=smtp-sink
    ports:
      - "8080:80"
    volumes:
      - sqlite:/var/lib/dbconfig-common/sqlite3/roundcube
networks:
  default:
    external:
      name: ${NETWORK}
